
PLUGS_KEY = 'RANDOM KEY'

DEVICES_INFO = {
        'DEVICE NAME': {'id': 'ID', 'ip': 'LOCAL IP ADDRESS', 'key': 'LOCAL KEY'}
        }

GROUPS = {
        'GROUP NAME': ['DEVICE NAME', 'DEVICE NAME', 'DEVICE NAME', 'DEVICE NAME']
}
